name: Test

on:
  push:
  pull_request:
    branches-ignore:
      - develop
env:
  NEXT_PUBLIC_FIREBASE_API_KEY: '${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}'
  NEXT_PUBLIC_FIREBASE_AUTU_DOMAIN: '${{secrets.NEXT_PUBLIC_FIREBASE_AUTU_DOMAIN}}'
  NEXT_PUBLIC_FIREBASE_DB_URL: '${{secrets.NEXT_PUBLIC_FIREBASE_DB_URL}}'
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: '${{secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID}}'
  NEXT_PUBLIC_FIREBASE_STORE: '${{secrets.NEXT_PUBLIC_FIREBASE_STORE}}'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: '[SETUP] Checkout'
        uses: actions/checkout@v2
      - name: '[SETUP] Node.js 16'
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - name: '[SETUP] Install dependencies'
        run: yarn
      - name: '[TEST] Run tests'
        run: yarn test:report
      - name: '[Test] Report tests'
        if: success() || failure()
        with:
          name: test-results
          path: junit.xml
          fail-on-error: 'false'
          reporter: jest-junit
          token: ${{ secrets.GITHUB_TOKEN }}
